<?php

namespace Zeta\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findAllProjects() {
        return $this->createQueryBuilder('a')
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true, 360, 'ArtistRepository_findAllOnlineArtistsForStage_'.strval($stage))
            ->getResult();

    }
}
