Zeta\ProjectBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: Zeta\ProjectBundle\Entity\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        project_id:
            type: integer
        file:
            type: string
            length: 255
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToOne:
        project:
            targetEntity: Project
            inversedBy: images
            joinColumn:
                name: project_id
                referencedColumnName: id