services:
    zeta.project.admin.project:
        class: Zeta\ProjectBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: projects, label: "Project" }
        arguments:
            - ~
            - Zeta\ProjectBundle\Entity\Project
            - ~
        calls:
            - [ setTranslationDomain, [ZetaProjectBundle]]

    zeta.project.admin.category:
        class: Zeta\ProjectBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: projects, label: "Category" }
        arguments:
            - ~
            - Zeta\ProjectBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [ZetaProjectBundle]]

    zeta.project.admin.image:
        class: Zeta\ProjectBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: projects, label: "Images" }
        arguments:
            - ~
            - Zeta\ProjectBundle\Entity\Image
            - ~
        calls:
            - [ setTranslationDomain, [ZetaProjectBundle]]