zeta_project_homepage:
    path:     /
    defaults: { _controller: ZetaProjectBundle:Default:index }



create_project:
    path:     /create/{name}
    defaults: { _controller: ZetaProjectBundle:Default:product }
